name: ShelterMC
version: 0.2.0
api-version: 1.14
main: com.gamelovemiku.sheltermc.ShelterMC
softdepend:
  - PlaceholderAPI

commands:
  testpl:
    description: Your description
    usage: /testpl
  ascotcity:
    description: Your description
    usage: /<command>